apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worpress-ingress
  namespace: wordpress
spec:
  rules:
  - host: "worpress.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wordpress
            port:
              number: 80
