apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
  namespace: wordpress
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data-pv-mysql"
